
version: 2

models:
    - name: scoring_data_bloom_live
      description: "scoring_data_bloom"
      columns:
          - name: store_number
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    # - name: my_second_dbt_model
    #   description: "A starter dbt model"
    #   columns:
    #       - name: id
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null
